switch from \" to '"' in shell lines
Otherwise the parser in ansible-git will bug out with

Traceback (most recent call last):
  File "command", line 2285, in <module>
    main()
  File "command", line 226, in main
    rc, out, err = module.run_command(args, executable=executable, use_unsafe_shell=shell)
  File "command", line 1928, in run_command
    to_clean_args = shlex.split(b_args)
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation

Thanks to @mgedmin in #ansible for the fix